### ISSUE TITLE
Usar o JGIT no lugar do sistema do git do sistema

### ISSUE THREAD

**Issue by mralves** [gems-uff/importmining#1]
Atualmente o importmining usa o git do sistema executando o comando diretamente, isso faz com que ele ele dependa que o sistema anfitrião tenha o git instalado e no path, é interessante perdermos essa dependência então acho uma boa ideia usar o JGIT para isso.

**Comment by mpjmuniz** [comment]
Qual o fundamento para perdermos essa dependência?

**Comment by mpjmuniz** [comment]
Repositórios públicos são copiados com sucesso; repositórios privados não.

**Comment by mralves** [comment]
Podemos deixar assim por enquanto já que o usuário pode clonar separado e usar.
Coloque esse cara para ser o default na hora de clonar
